# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'
  name: 'shichao-mac-agent'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      bash <(curl -s  https://detect.synopsys.com/detect.sh) \
        --blackduck.url=https://hubsig.blackducksoftware.com/ \
        --blackduck.trust.cert=true  \
        --blackduck.api.token=ZjJkYjlkMjAtMTFkZS00YjljLWE0OTUtOTZhYjYwMjUwMWIxOmE3NWEwMDk3LTUyYjQtNDMzYi1hMzNjLWE4ZTU1Mzk3ZmViMw== \
        --detect.project.name=WebGoat8  \
        --detect.project.version.name=M25 \
        --detect.polaris.enable=true  \
        --polaris.url="https://sipse.polaris.synopsys.com"  \
        --polaris.arguments="--\ mvn\ -DskipTests\ clean\ install" \
        --polaris.access.token="23shvlrfe94jt1qgo5j5pjmib07b2pi09ml1lpq4iuu7cigdj7cg"
